name: AI Code Review and Test Suggestions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python -m pytest tests/

    - name: Extract Git Diff
      id: get_diff
      run: |
        git fetch origin main
        echo "Debug: Calculating diff between PR branch and main branch..."
        # Compute the diff between the PR branch and the main branch
        DIFF_CONTENT=$(git diff origin/main)
        echo "diff<<EOF" >> $GITHUB_OUTPUT
        echo "$DIFF_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate Code Review Feedback via OpenAI API
      id: ai_code_review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Debug: Preparing API call for code review using jq..."
        PAYLOAD=$(jq -n --arg diff "${{ steps.get_diff.outputs.diff }}" '{
          model: "gpt-4o-mini",
          messages: [
            {
              role: "system",
              content: "You are an expert code reviewer. Analyze the code changes and provide detailed feedback on code quality, potential issues, and suggestions for improvement."
            },
            {
              role: "user",
              content: ("Please review these code changes:\n\n" + $diff)
            }
          ],
          temperature: 0.7
        }')
        
        echo "Debug: Raw API Payload for Code Review:"
        echo "$PAYLOAD"
        
        echo "Debug: Making API call for code review..."
        RESPONSE=$(curl -v https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d "$PAYLOAD")
        
        echo "Debug: Raw API Response for Code Review:"
        echo "$RESPONSE"
        
        echo "Debug: Extracted Code Review Feedback:"
        REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
        echo "$REVIEW"
        
        echo "review_content<<EOF" >> $GITHUB_OUTPUT
        echo "$REVIEW" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate Unit Test Suggestions via OpenAI API
      id: ai_unit_tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Debug: Preparing API call for unit test suggestions using jq..."
        PAYLOAD=$(jq -n --arg diff "${{ steps.get_diff.outputs.diff }}" '{
          model: "gpt-4o-mini",
          messages: [
            {
              role: "system",
              content: "You are an expert unit test writer. Based on the provided code changes, suggest detailed Python unit tests using the unittest framework."
            },
            {
              role: "user",
              content: ("Please generate unit tests for these code changes:\n\n" + $diff)
            }
          ],
          temperature: 0.7
        }')
        
        echo "Debug: Raw API Payload for Unit Test Suggestions:"
        echo "$PAYLOAD"
        
        echo "Debug: Making API call for unit test suggestions..."
        RESPONSE=$(curl -v https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d "$PAYLOAD")
        
        echo "Debug: Raw API Response for Unit Test Suggestions:"
        echo "$RESPONSE"
        
        echo "Debug: Extracted Unit Test Suggestions:"
        TESTS=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
        echo "$TESTS"
        
        echo "unit_test_content<<EOF" >> $GITHUB_OUTPUT
        echo "$TESTS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post Review Comment
      uses: actions/github-script@v6
      with:
        script: |
          const codeReview = process.env.CODE_REVIEW_CONTENT;
          const unitTests = process.env.UNIT_TEST_CONTENT;
          const comment = `## AI Code Review Feedback\n\n### Code Review\n\n${codeReview}\n\n### Unit Test Suggestions\n\n${unitTests}`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });
      env:
        CODE_REVIEW_CONTENT: ${{ steps.ai_code_review.outputs.review_content }}
        UNIT_TEST_CONTENT: ${{ steps.ai_unit_tests.outputs.unit_test_content }}
